name: Build, Check, and Release

permissions:
  contents: write
  packages: write
  id-token: write

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  pull_request:

jobs:
  test_integration:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.9","3.10","3.11","3.12","3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-poetry
        with:
          python: ${{ matrix.python }}
          pytest-path: tests/integration

  build:
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    needs:
      - test_integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.9 (with pip cache)
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: pip
          cache-dependency-path: |
            **/pyproject.toml
            **/poetry.lock
            **/requirements*.txt

      - name: Build distribution
        run: |
          sh setup.sh
          source .venv/bin/activate
          for sp in hatch pdm poetry; do
            pushd "$sp"
            poetry build -o ../dist/
            popd
          done

      - id: get_version
        name: Extract version from wheels
        shell: bash
        run: |
          python - <<'PY'
          import os, re, sys, pathlib
          dist = pathlib.Path("dist")
          wheels = sorted(dist.glob("pychub_hatch_plugin-*.whl"))
          if not wheels:
              print("No hatch plugin wheel found in dist/", file=sys.stderr)
              sys.exit(1)
          whl = wheels[0]  # or: next(iter(wheels))
          m = re.search(r"pychub_hatch_plugin-([0-9]+\.[0-9]+\.[0-9]+)-", whl.name)
          if not m:
              print(f"Cannot parse MAJOR.MINOR.PATCH from {whl.name}", file=sys.stderr)
              sys.exit(1)
          ver = m.group(1)
          print("Detected version:", ver)
          with open(os.environ["GITHUB_OUTPUT"], "a") as f:
              f.write(f"version={ver}\n")
          PY

      - name: Upload hatch dist
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  check:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.9 (with pip cache)
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: pip
          cache-dependency-path: |
            **/pyproject.toml
            **/poetry.lock
            **/requirements*.txt

      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Twine check
        run: |
          sh setup.sh
          source .venv/bin/activate
          pip install -U twine
          twine check dist/*

  publish_test_pypi:
    outputs:
      published: ${{ (steps.upload.conclusion == 'success') && 'true' || 'false' }}
    needs: [check]
    runs-on: ubuntu-latest
    if: |
      github.ref == 'refs/heads/main'
    environment: pypi
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build distribution
        run: |
          sh setup.sh
          source .venv/bin/activate
          for sp in hatch pdm poetry; do
            pushd "$sp"
            poetry build -o ../dist/
            popd
          done

      - name: Publish to TestPyPI
        id: upload
        if: github.ref == 'refs/heads/main'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TESTPYPI_ACCOUNT_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          packages-dir: dist
          skip-existing: true

  publish:
    outputs:
      published: ${{ (steps.upload.conclusion == 'success') && 'true' || 'false' }}
    needs: [check]
    runs-on: ubuntu-latest
    if: |
      startsWith(github.ref, 'refs/tags/')
    environment: pypi
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build distribution
        run: |
          sh setup.sh
          source .venv/bin/activate
          for sp in hatch pdm poetry; do
            pushd "$sp"
            poetry build -o ../dist/
            popd
          done

      - name: Publish to PyPI.org
        id: upload
        if: startsWith(github.ref, 'refs/tags/')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_ACCOUNT_TOKEN }}
          repository-url: https://upload.pypi.org/legacy/
          packages-dir: dist
          skip-existing: true

      # --- GitHub Release (only on tags) ---
      - name: Create GitHub Release and upload wheel
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*

  post-publish-smoke-test:
    needs: [publish, publish_test_pypi]
    if: ${{ always() && (
          needs.publish.outputs.published == 'true' ||
          needs.publish_test_pypi.outputs.published == 'true'
        ) }}
    runs-on: ubuntu-latest
    env:
      INDEX_URL: ${{ (fromJSON(needs.publish.outputs.published || 'false') && 'https://pypi.org/simple/') || 'https://test.pypi.org/simple/' }}
      VER: ${{ needs.build.outputs.version }}
    steps:
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install from index and assert entrypoints
        shell: bash
        run: |
          python -m venv .v && source .v/bin/activate
          python -m pip install -U pip
          EXTRA=""
          if [ "$INDEX_URL" = "https://test.pypi.org/simple/" ]; then
            EXTRA="--extra-index-url https://pypi.org/simple/"
          fi
          python -m pip install --index-url "$INDEX_URL" $EXTRA \
          "pychub-hatch-plugin==$VER" "pychub-pdm-plugin==$VER" "pychub-poetry-plugin==$VER"
          python - <<'PY'
          from importlib.metadata import entry_points
          assert any(ep.name=="pychub" for ep in entry_points(group="hatch")), "hatch hook missing"
          assert any(ep.name=="pychub" for ep in entry_points(group="pdm.build.hook")), "pdm hook missing"
          assert any(ep.name=="pychub-poetry-plugin" for ep in entry_points(group="poetry.application.plugin")), "poetry plugin missing"
          print("Post-publishing verification OK")
          PY
